### PR TITLE
chore: null safety migration

### PR DESCRIPTION
**Pull request by larssn**
Speaks for itself 🙂

On another note: Seeing as this repo is the repo linked from pub.dev, would you mind adding an issue tracker?

### CODE REVIEW

**Review by nohli — APPROVED** [review]

**Comment by nosmirck** [comment]
please merge :)

**Review by nosmirck — APPROVED** [review]

**Comment by armandojimenez** [comment]
Thanks for this! only package left for me

**Comment by armandojimenez** [comment]
Any update on when will this be merged?

**Comment by BeomJobs** [comment]
Plz merge 😄

**Comment by armandojimenez** [comment]
How can I point to this branch? really need the package migrated

**Comment by larssn** [comment]
> How can I point to this branch? really need the package migrated

Put this in your pubspec.yaml under dependencies:
```
   flutter_nfc_acs:
     git:
       url: https://github.com/larssn/flutter_vibrate
```

**Comment by max-hardcoder** [comment]
@rodydavis is that possible to merge ? Thank's

**Comment by obrunsmann** [comment]
@rodydavis are you able to maintain this repo furthermore? Do you need any assistance?

**Comment by yasinarik** [comment]
> > How can I point to this branch? really need the package migrated
> 
> Put this in your pubspec.yaml under dependencies:
> 
> ```
>    flutter_vibrate:
>      git:
>        url: https://github.com/larssn/flutter_vibrate
> ```

Umm, I wrote like this on pubspec.yaml and got the package. However, I am getting this error:

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method vibrate on channel vibrate)
#0      MethodChannel._invokeMethod 
```

Probably, the package isn't installed with the plugins. How to do that since I can't wait for a null-safety merge. 
@larssn @nohli @nosmirck Thanks a lot!

**Comment by nohli** [comment]
@yasinarik please copy your pubspec.yaml here (in a code block).

**Comment by larssn** [comment]
@yasinarik If you have a lot of plugins - new and old, you could be running into this issue (we did): https://github.com/flutter/flutter/issues/75416

**Comment by yasinarik** [comment]
@nohli @larssn Sorry for pinging you guys. I think I have solved it by deleting `pubspec.lock` file manually and running `flutter clean`, `flutter pub get`. I would have tried that before asking, my bad.

BTW, I have seen that there are already 2 null-safety pull requests waiting for a merge. The owner of the package seems unavailable for a reason. Have you ever thought about creating a new package supporting null-safety with the files from the current package, and then giving credits to @rodydavis  and @clovisnicolas?

If I couldn't see that comment:
>   flutter_vibrate:
     git:
       url: https://github.com/larssn/flutter_vibrate

I would be unable to use this package. So many people might miss it too.

Anyways, I really appreciate that you answered almost immediately. Have a great day!

**Review by yasinarik — APPROVED** [review]

**Comment by rodydavis** [comment]
Updated for null safety in another merge. Will publish soon

**Pull request closed without merging**
