### PR TITLE
Migrate to android v2 embedding

### PR DESCRIPTION
**Pull request by nohli**
There is a warning regarding the v2 migration during every flutter build, even just on `pub get`.

The other plugins were really quick with updates - this is (for me) the last plugin that hasn't been updated yet.
A new version on pub.dev would be great! :)

This PR fixes it.

### CODE REVIEW

**Comment by sanekyy** [comment]
Let's merge it!:)

**Comment by nohli** [comment]
> Let's merge it!:)

@sanekyy could you also test it on a real Android device before it gets merged/published?

**Comment by kakudenbuzo** [comment]
@nohli 
On my android device, it worked!

**Comment by nohli** [comment]
@rodydavis Idk if you already saw this :)

**Comment by armandojimenez** [comment]
Any plans to merge this?? :D

**Comment by PhilipPurwoko** [comment]
Just to be clear, this is the exact warning message shown
```
The plugin `flutter_vibrate` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

This branch has no conflicts. Please merge soon 😄

**Comment by designedbyclu** [comment]
@rodydavis any plan to merge it soon?

**Comment by rodydavis** [comment]
I will publish today

**Comment by rodydavis** [comment]
published 1.2.0!

**Pull request merged**
