### PR TITLE
Fix SWIFT_VERSION

### PR DESCRIPTION
**Pull request by Realank**

### CODE REVIEW

**Comment by jakusb** [comment]
I cannot find an issues page to register a new issue:
The plugin `flutter_vibrate` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these
deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by FufferKS** [comment]
Hi, any update on this PR? 
This fix would be much appreciated!

I'm running into:
```
- `flutter_vibrate` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by nohli** [comment]
> I cannot find an issues page to register a new issue:
> The plugin `flutter_vibrate` uses a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these
> deprecated APIs.
> If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

@jakusb @rodydavis https://github.com/rodydavis/flutter_vibrate/pull/17

**Comment by rodydavis** [comment]
LGTM

**Comment by rodydavis** [comment]
published! 01.3.0

**Pull request merged**
