### PR TITLE
Update Android Dependencies

### PR DESCRIPTION
**Pull request by dwach414**
# Update Build Gradle

## Changes
- Update the build gradle to target a higher android version and to use a higher version of the build tools to prevent errors in linking release build.

### CODE REVIEW

**Comment by miguelcmedeiros** [comment]
@dwach414 @rodydavis 
I just verified and this PR enables the plugin to be used in flutter v1.12.13.
With this new version of flutter all plugins need to have compileSdkVersion set to 28. See comment from @blasten in https://github.com/flutter/flutter/issues/46881#issuecomment-565174872

It would be great if this if this lands soon :)

**Comment by rodydavis** [comment]
Sweet thank you!

**Comment by miguelcmedeiros** [comment]
@rodydavis damm that was fast 😳🎉

**Comment by rodydavis** [comment]
😉💪🏻

**Comment by miguelcmedeiros** [comment]
@rodydavis, is it possible to publish a new version with this PR?
I would like to update my project and if possible use pub.dev :)

**Comment by TheBestMoshe** [comment]
When will this update be released?

**Comment by Spikes042** [comment]
Welp!
Looks like we're in a bit of a pickle

**Comment by rodydavis** [comment]
This is my fork of the plugin!

**Comment by rodydavis** [comment]
I will just publish a plugin with new name I guess!

**Comment by Spikes042** [comment]
Oh just noticed.

Your repo is linked from pub.dev btw.
Well, actually linked to appleeducate/flutter_vibrate which redirects to yours

**Comment by rodydavis** [comment]
Ok i published my version of this fork: https://pub.dev/packages/flutter_vibrate

**Pull request merged**
